# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 10:28
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('endtime', models.DateTimeField()),
                ('scoringtype', models.CharField(choices=[('=', '1 pass = 1 point'), ('%', 'Percent passed'), ('s', 'Sum of square of passes'), ('S', 'Sum of square of percent passed'), ('1', 'All passed = 1 point')], max_length=1)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('timetorun', models.SmallIntegerField()),
                ('author', models.CharField(default='admin', max_length=150, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('submission', models.FileField(max_length=10240, upload_to='user_submissions')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icm.Competition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icm.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testinput', models.TextField()),
                ('testoutput', models.TextField()),
                ('weighting', models.SmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icm.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('A', 'Admin'), ('Q', 'Question setter'), ('C', 'Competitior')], max_length=1)),
                ('compname', models.CharField(max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='questions',
            field=models.ManyToManyField(to='icm.Question'),
        ),
    ]
